name: Tinderbox
author: Tinderbox
main: net.inabsentia.bukkit.Tinderbox.Tinderbox
version: 0.1
commands:
  tb:
    description: Toggle the lighting rod on and off
    usage: /<command> [option] (on|off)